### ISSUE TITLE
[15.0][BUG] mrp_production_grouped_by_product

### ISSUE THREAD

**Issue by Bart-dh** [OCA/manufacture#1058]
https://github.com/OCA/manufacture/blob/f520b3c15de3e1e4cba4aa11dfdfed6620646ef2/mrp_production_grouped_by_product/models/mrp_production.py#L68

Case: date_deadline is 30/06/2023 (30th of june)
Method wants to change date by adding +1 to date.day -> tries to modfiy date to 31 june which doesn't exist

Error log:

  File "/opt/odoo15/odoo/addons/sale_crm/models/sale_order.py", line 15, in action_confirm
    return super(SaleOrder, self.with_context({k:v for k,v in self._context.items() if k != 'default_tag_ids'})).action_confirm()
  File "/opt/odoo15/odoo/addons/website_sale/models/sale_order.py", line 390, in action_confirm
    res = super(SaleOrder, self).action_confirm()
  File "/opt/odoo15/odoo/addons/sale_management/models/sale_order.py", line 153, in action_confirm
    res = super(SaleOrder, self).action_confirm()
  File "/opt/odoo15/odoo/addons/sale/models/sale_order.py", line 998, in action_confirm
    self.with_context(context)._action_confirm()
  File "/opt/odoo15/odoo/addons/sale_project/models/sale_order.py", line 55, in _action_confirm
    result = super()._action_confirm()
  File "/opt/odoo15/odoo/addons/sale_stock/models/sale_order.py", line 149, in _action_confirm
    self.order_line._action_launch_stock_rule()
  File "/opt/odoo15/odoo/addons/sale_stock/models/sale_order.py", line 596, in _action_launch_stock_rule
    pickings_to_confirm.action_confirm()
  File "/opt/odoo15/odoo/addons/stock/models/stock_picking.py", line 799, in action_confirm
    self.mapped('move_lines').filtered(lambda move: move.state not in ('draft', 'cancel', 'done'))._trigger_scheduler()
  File "/opt/odoo15/odoo/addons/stock/models/stock_move.py", line 2014, in _trigger_scheduler
    orderpoints.with_context(origins=orderpoints_context_by_company[company])._procure_orderpoint_confirm(
  File "/opt/odoo15/odoo/addons/stock/models/stock_orderpoint.py", line 534, in _procure_orderpoint_confirm
    self.env['procurement.group'].with_context(from_orderpoint=True).run(procurements, raise_user_error=raise_user_error)
  File "/opt/odoo15/odoo/addons/purchase_stock/models/stock.py", line 362, in run
    return super().run(procurements, raise_user_error=raise_user_error)
  File "/opt/odoo15/odoo/addons/mrp/models/stock_rule.py", line 228, in run
    return super(ProcurementGroup, self).run(procurements_without_kit, raise_user_error=raise_user_error)
  File "/opt/odoo15/odoo/addons/stock/models/stock_rule.py", line 463, in run
    getattr(self.env['stock.rule'], '_run_%s' % action)(procurements)
  File "/opt/odoo15/custom_addons/mrp_production_grouped_by_product/models/stock_rule.py", line 12, in _run_manufacture
    return super(
  File "/opt/odoo15/odoo/addons/mrp/models/stock_rule.py", line 60, in _run_manufacture
    productions = self.env['mrp.production'].with_user(SUPERUSER_ID).sudo().with_company(company_id).create(productions_values)
  File "<decorator-gen-279>", line 2, in create
  File "/opt/odoo15/odoo/odoo/api.py", line 394, in _model_create_single
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/opt/odoo15/odoo/odoo/api.py", line 394, in <genexpr>
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/opt/odoo15/custom_addons/mrp_production_grouped_by_product/models/mrp_production.py", line 95, in create
    mo = self._find_grouping_target(vals)
  File "/opt/odoo15/custom_addons/mrp_production_grouped_by_product/models/mrp_production.py", line 86, in _find_grouping_target
    self._get_grouping_target_domain(vals), limit=1
  File "/opt/odoo15/custom_addons/mrp_production_grouped_by_product/models/mrp_production.py", line 68, in _get_grouping_target_domain
    date_end = date.replace(
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo15/odoo/odoo/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo15/odoo/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: day is out of range for month

**Comment by Bart-dh** [comment]
@LoisRForgeFlow hi Lois. I see you've previously fixed bugs with this module. Could you perhaps check this issue? It would be much appreciated!

**Comment by Sibert-Aerts** [comment]
This issue is addressed by my pull request: https://github.com/OCA/manufacture/pull/1104
