### ISSUE TITLE
[8.0][mrp_production_estimated_cost] : Error when clicking on Costs Analysis button

### ISSUE THREAD

**Issue by mamaf** [OCA/manufacture#106]
In a virtual Manufacturing order, when clicking on Costs Analysis button :

Traceback (most recent call last):
  File "/home/it-6it/aoe-dev_80/base/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/it-6it/aoe-dev_80/base/openerp/http.py", line 574, in dispatch
    result = self._call_function(*_self.params)
  File "/home/it-6it/aoe-dev_80/base/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/home/it-6it/aoe-dev_80/base/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/home/it-6it/aoe-dev_80/base/openerp/http.py", line 307, in checked_call
    return self.endpoint(_a, *_kw)
  File "/home/it-6it/aoe-dev_80/base/openerp/http.py", line 803, in __call__
    return self.method(_args, *_kw)
  File "/home/it-6it/aoe-dev_80/base/openerp/http.py", line 403, in response_wrap
    response = f(_args, *_kw)
  File "/home/it-6it/aoe-dev_80/base/addons/web/controllers/main.py", line 952, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/it-6it/aoe-dev_80/base/addons/web/controllers/main.py", line 940, in _call_kw
    return checked_call(request.db, _args, *_kwargs)
  File "/home/it-6it/aoe-dev_80/base/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/home/it-6it/aoe-dev_80/base/addons/web/controllers/main.py", line 939, in checked_call
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/home/it-6it/aoe-dev_80/base/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/it-6it/aoe-dev_80/base/openerp/api.py", line 363, in old_api
    result = method(recs, _args, *_kwargs)
  File "/home/it-6it/aoe-dev_80/addons-partners/mrp_production_estimated_cost/models/mrp_production.py", line 81, in action_show_estimated_costs
    'mrp_project.account_analytic_line_mrp_search_view')
  File "/home/it-6it/aoe-dev_80/base/openerp/api.py", line 742, in ref
    return self['ir.model.data'].xmlid_to_object(xml_id, raise_if_not_found=raise_if_not_found)
  File "/home/it-6it/aoe-dev_80/base/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/it-6it/aoe-dev_80/base/openerp/api.py", line 463, in new_api
    result = method(self._model, cr, uid, _args, *_kwargs)
  File "/home/it-6it/aoe-dev_80/base/openerp/addons/base/ir/ir_model.py", line 950, in xmlid_to_object
    t = self.xmlid_to_res_model_res_id(cr, uid, xmlid, raise_if_not_found)
  File "/home/it-6it/aoe-dev_80/base/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/it-6it/aoe-dev_80/base/openerp/addons/base/ir/ir_model.py", line 936, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(cr, uid, xmlid)[1:3]
  File "/home/it-6it/aoe-dev_80/base/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "<string>", line 2, in xmlid_lookup
  File "/home/it-6it/aoe-dev_80/base/openerp/tools/cache.py", line 74, in lookup
    value = d[key] = self.method(_args, *_kwargs)
  File "/home/it-6it/aoe-dev_80/base/openerp/addons/base/ir/ir_model.py", line 926, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % (xmlid))
ValueError: External ID not found in the system: mrp_project.account_analytic_line_mrp_search_view

**Comment by LoisRForgeFlow** [comment]
Closing due to aging, please feel free to reopen.
