### ISSUE TITLE
[15.0] mrp_account_bom_attribute_match: error in tests

### ISSUE THREAD

**Issue by ChristianSantamaria** [OCA/manufacture#1088]
In PR #1048 the following error is occurring in Runboat, could you take a look at it @ivandodorovich?:
```
2023-09-01 06:21:38,598 252 ERROR odoo unittest.suite: ERROR: setUpClass (odoo.addons.mrp_bom_attribute_match.tests.test_mrp_bom_attribute_match.TestMrpBomAttributeMatch)
Traceback (most recent call last):
  File "/__w/manufacture/manufacture/mrp_bom_attribute_match/tests/common.py", line 142, in setUpClass
    cls.p3_bom_id = cls._create_bom(
  File "/__w/manufacture/manufacture/mrp_bom_attribute_match/tests/common.py", line 162, in _create_bom
    for vals in line_form_vals:
  File "/opt/odoo/odoo/tests/common.py", line 2185, in __exit__
    self.save()
  File "/opt/odoo/odoo/tests/common.py", line 2204, in save
    r = self._model.create(values)
  File "<decorator-gen-123>", line 2, in create
  File "/opt/odoo/odoo/api.py", line 412, in _model_create_multi
    return create(self, [arg])
  File "/opt/odoo/addons/mail/models/mail_thread.py", line 261, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-67>", line 2, in create
  File "/opt/odoo/odoo/api.py", line 413, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/odoo/addons/base/models/ir_fields.py", line 613, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "/opt/odoo/odoo/api.py", line 413, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/odoo/models.py", line 4088, in create
    records = self._create(data_list)
  File "/opt/odoo/odoo/models.py", line 4253, in _create
    records._validate_fields(name for data in data_list for name in data['stored'])
  File "/opt/odoo/odoo/models.py", line 1371, in _validate_fields
    check(self)
  File "/opt/odoo/addons/mrp/models/mrp_bom.py", line 152, in _check_bom_cycle
    _check_cycle(bom.bom_line_ids.product_id, finished_products)
  File "/opt/odoo/addons/mrp/models/mrp_bom.py", line 131, in _check_cycle
    _check_cycle(subcomponents, finished_products | component)
  File "/opt/odoo/addons/mrp/models/mrp_bom.py", line 131, in _check_cycle
    _check_cycle(subcomponents, finished_products | component)
  File "/opt/odoo/addons/mrp/models/mrp_bom.py", line 118, in _check_cycle
    raise ValidationError(_("The current configuration is incorrect because it would create a cycle "
odoo.exceptions.ValidationError: The current configuration is incorrect because it would create a cycle between these products: P3, P1, P2
```.

**Comment by HaraldPanten** [comment]
@ivantodorovich

**Comment by ValentinVinagre** [comment]
@etobella solved 👍🏻

**Comment by HaraldPanten** [comment]
@ChristianSantamaria you can close this issue. It's been solved in https://github.com/OCA/manufacture/pull/1090

**Comment by HaraldPanten** [comment]
@etobella this issue can be closed 👍

Update: sorry I didn't refresh the page.
