### ISSUE TITLE
[8.0][mrp_project] Error when creating assignation to a task

### ISSUE THREAD

**Issue by mamaf** [OCA/manufacture#109]
In Work order, operators time tab, when adding a line and creating a task to assign a person, I get this error :
Traceback (most recent call last):
  File "/home/it-6it/aoe-dev_80/base/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/it-6it/aoe-dev_80/base/openerp/http.py", line 574, in dispatch
    result = self._call_function(*_self.params)
  File "/home/it-6it/aoe-dev_80/base/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/home/it-6it/aoe-dev_80/base/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/home/it-6it/aoe-dev_80/base/openerp/http.py", line 307, in checked_call
    return self.endpoint(_a, *_kw)
  File "/home/it-6it/aoe-dev_80/base/openerp/http.py", line 803, in __call__
    return self.method(_args, *_kw)
  File "/home/it-6it/aoe-dev_80/base/openerp/http.py", line 403, in response_wrap
    response = f(_args, *_kw)
  File "/home/it-6it/aoe-dev_80/base/addons/web/controllers/main.py", line 948, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/it-6it/aoe-dev_80/base/addons/web/controllers/main.py", line 940, in _call_kw
    return checked_call(request.db, _args, *_kwargs)
  File "/home/it-6it/aoe-dev_80/base/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/home/it-6it/aoe-dev_80/base/addons/web/controllers/main.py", line 939, in checked_call
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/home/it-6it/aoe-dev_80/base/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/it-6it/aoe-dev_80/base/openerp/api.py", line 363, in old_api
    result = method(recs, _args, *_kwargs)
  File "/home/it-6it/aoe-dev_80/addons-partners/mrp_project/models/mrp_production.py", line 98, in write
    production=self.production_id)).write(vals)
  File "/home/it-6it/aoe-dev_80/base/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/it-6it/aoe-dev_80/addons-partners/mrp_operations_extension/models/mrp_production.py", line 135, in write
    update=update)
  File "/home/it-6it/aoe-dev_80/base/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/it-6it/aoe-dev_80/base/openerp/api.py", line 547, in new_api
    result = method(self._model, cr, uid, self.ids, _args, *_kwargs)
  File "/home/it-6it/aoe-dev_80/base/addons/mrp_operations/mrp_operations.py", line 134, in write
    result = super(mrp_production_workcenter_line, self).write(cr, uid, ids, vals, context=context)
  File "/home/it-6it/aoe-dev_80/base/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/it-6it/aoe-dev_80/base/addons/mail/mail_thread.py", line 432, in write
    result = super(mail_thread, self).write(cr, uid, ids, values, context=context)
  File "/home/it-6it/aoe-dev_80/base/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/it-6it/aoe-dev_80/base/openerp/api.py", line 363, in old_api
    result = method(recs, _args, *_kwargs)
  File "/home/it-6it/aoe-dev_80/base/openerp/models.py", line 3779, in write
    self._write(old_vals)
  File "/home/it-6it/aoe-dev_80/base/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/it-6it/aoe-dev_80/base/openerp/api.py", line 547, in new_api
    result = method(self._model, cr, uid, self.ids, _args, *_kwargs)
  File "/home/it-6it/aoe-dev_80/base/openerp/models.py", line 3922, in _write
    result += self._columns[field].set(cr, self, id, field, vals[field], user, context=rel_context) or []
  File "/home/it-6it/aoe-dev_80/base/openerp/osv/fields.py", line 811, in set
    id_new = obj.create(cr, user, act[2], context=context)
  File "/home/it-6it/aoe-dev_80/base/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/it-6it/aoe-dev_80/base/addons/project_timesheet/project_timesheet.py", line 161, in create
    vals['hr_analytic_timesheet_id'] = self._create_analytic_entries(cr, uid, vals, context=context)
  File "/home/it-6it/aoe-dev_80/base/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/it-6it/aoe-dev_80/base/openerp/api.py", line 336, in old_api
    result = method(recs, _args, *_kwargs)
  File "/home/it-6it/aoe-dev_80/addons-partners/mrp_project/models/project_task_work.py", line 37, in _create_analytic_entries
    workorder=task.workorder))._create_analytic_entries(vals)
  File "/home/it-6it/aoe-dev_80/base/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/it-6it/aoe-dev_80/base/openerp/api.py", line 463, in new_api
    result = method(self._model, cr, uid, _args, *_kwargs)
  File "/home/it-6it/aoe-dev_80/base/addons/project_timesheet/project_timesheet.py", line 117, in _create_analytic_entries
    vals_line['name'] = '%s: %s' % (tools.ustr(task_obj.name), tools.ustr(vals['name'] or '/'))
KeyError: 'name'

**Comment by pedrobaeza** [comment]
Task are created automatically, so no need to create it by hand. Anyway, please tell me the exact steps you have made for reproducing the error.

**Comment by mamaf** [comment]
In a work order, in modification, I go to operator time and create a line, then create a task
When saving the work order, I have the error

I have never seen any lines in this tab, What do I have to parameterize so that tasks are created automatically ?
The need is to record human (employee) time and cost

**Comment by anajuaristi** [comment]
If you set the number of workers on routing line, tasks will be created
automatically.
Notice that you need to activate workers option in manufacturing
configuration form, otherwise the field could be invisible on routing line
and operations master where you can pre-set the exact workers that will be
assigned as task responsible.

**Comment by mamaf** [comment]
> Notice that you need to activate workers option in manufacturing

How do you do that ? Where is the "manufacturing configuration form" ?

And how do you see mlachine and operator planning ? (are we obliged to use project management ??)

**Comment by anajuaristi** [comment]
Menu Configuration/manufacturing
And yes. We designed odoomrp not to reinvent the wheel so as in odoo people
registers time in tasks we linked both modules adding tasks to Mos and Wos

**Comment by LoisRForgeFlow** [comment]
No more answer, I consider the issue solved.
