### ISSUE TITLE
[8.0] quality_control_stock: Expected singleton exception with multiple triggers per picking-route/product

### ISSUE THREAD

**Issue by jkrenzer** [OCA/manufacture#139]
Hi!

I stumbled across an exception when trying to confirm a picking in the stock picking wizard: When having multiple triggers for one picking type on one product, we get a singleton-exception:

```
Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 543, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 580, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/openerp/http.py", line 313, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/openerp/http.py", line 809, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/openerp/http.py", line 409, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 439, in old_api
    result = new_api(recs, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 443, in new_api
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/opt/odoo/addons/stock/wizard/stock_transfer_details.py", line 109, in do_detailed_transfer
    self.picking_id.do_transfer()
  File "/opt/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 592, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **old_kwargs)
  File "/opt/odoo/addons/stock_invoice_directly/stock_invoice_directly.py", line 37, in do_transfer
    res = super(stock_picking, self).do_transfer(cr, uid, picking_ids, context=context)
  File "/opt/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 399, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/addons/quality_control_stock/models/stock_picking.py", line 48, in do_transfer
    if qc_trigger.partner_selectable else False)
  File "/opt/odoo/openerp/fields.py", line 825, in __get__
    record.ensure_one()
  File "/opt/odoo/openerp/models.py", line 5319, in ensure_one
    raise except_orm("ValueError", "Expected singleton: %s" % self)
except_orm: ('ValueError', 'Expected singleton: qc.trigger(2, 12)')
```

I hacked a quick patch because we need to do our pickings here immediately. It seems to work so far, but currently I have zero time for further testing.

[quality_control_stock.patch.txt](https://github.com/OCA/manufacture/files/339168/quality_control_stock.patch.txt)

Please have a look. :)

Cheers

Jörn

**Comment by LoisRForgeFlow** [comment]
Closing due to aging, please feel free to reopen if you still experience the issue.
