### ISSUE TITLE
Demand in MRP multi level

### ISSUE THREAD

**Issue by ccandito** [OCA/manufacture#300]
Dear All,
I'm started to test the "MRP multi level" module.
Unfortunately I did not grab how the independent requirements (the demand) has to be entered.
I've tried to use the "stock demand planning" for this purposes and when running the "mrp multi level" the following message comes up: "No MRP product found".
Thanks in advance
Claudio

**Comment by JordiBForgeFlow** [comment]
You have to create an mrp.area first.
Then you can either define stock estimates (https://github.com/OCA/manufacture/blob/11.0/mrp_multi_level/wizards/mrp_multi_level.py#L357)
or you can place actual demand (confirmed stock moves) in the selected mrp area

**Comment by ccandito** [comment]
Dear Jordi,
thanks for your prompt reply.
I've created an MRP Area for my WH and its main location.
I've also entered for some products some stock estimations for their demand
in the future.
unfortunately I'm receiving the same message "No MRP product found" when
running MRP multi level.
Regards
claudio

Il giorno lun 27 ago 2018 alle ore 13:27 Jordi Ballester Alomar <
notifications@github.com> ha scritto:

**Comment by ccandito** [comment]
Dear Jordi,
I've entered 1 day in mrp_nbr_days and the following short dump has
occurred:
Regards
claudio

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo11/odoo-dev/odoo/odoo/http.py", line 650, in
_handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo11/odoo-dev/odoo/odoo/http.py", line 310, in
_handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo11/odoo-dev/odoo/odoo/tools/pycompat.py", line 87, in
reraise
    raise value
  File "/home/odoo11/odoo-dev/odoo/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo11/odoo-dev/odoo/odoo/http.py", line 342, in
_call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo11/odoo-dev/odoo/odoo/service/model.py", line 97, in
wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo11/odoo-dev/odoo/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo11/odoo-dev/odoo/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/home/odoo11/odoo-dev/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo11/odoo-dev/odoo/addons/web/controllers/main.py", line
938, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo11/odoo-dev/odoo/addons/web/controllers/main.py", line
926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo11/odoo-dev/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/odoo11/odoo-dev/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File
"/home/odoo11/odoo-dev/odoo/addons/mrp_multi_level/wizards/mrp_multi_level.py",
line 767, in run_mrp_multi_level
    self._mrp_calculation(mrp_lowest_llc)
  File
"/home/odoo11/odoo-dev/odoo/addons/mrp_multi_level/wizards/mrp_multi_level.py",
line 617, in _mrp_calculation
    nbr_create, mrp_product)
  File
"/home/odoo11/odoo-dev/odoo/addons/mrp_multi_level/wizards/mrp_multi_level.py",
line 540, in _init_mrp_move_grouped_demand
    mrp_product - last_qty
TypeError: unsupported operand type(s) for -: 'float' and 'mrp.product'

Il giorno lun 27 ago 2018 alle ore 18:42 Claudio Candito <
claudiocandito@gmail.com> ha scritto:

**Comment by JordiBForgeFlow** [comment]
Try to create a stock picking from WH to customer, and see if it runs ok.

**Comment by ccandito** [comment]
I've create two sales orders: one MTS and the second with MTO procedure.
Only for the second case, the procurement is triggered by the MRP multi level procedure for the components only (wrong!!), not for the semifinished material in sales order (right!!).
in the first case, nothing's happened.
Moreover, I've tried to convert the suggested inventory procurement items and the following short dump has occurred:
Regards
claudio 

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo11/odoo-dev/odoo/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo11/odoo-dev/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo11/odoo-dev/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/odoo11/odoo-dev/odoo/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo11/odoo-dev/odoo/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo11/odoo-dev/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo11/odoo-dev/odoo/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo11/odoo-dev/odoo/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/home/odoo11/odoo-dev/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo11/odoo-dev/odoo/addons/web/controllers/main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo11/odoo-dev/odoo/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo11/odoo-dev/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/odoo11/odoo-dev/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo11/odoo-dev/odoo/addons/mrp_multi_level/wizards/mrp_inventory_procure.py", line 81, in make_procurement
    values
  File "/home/odoo11/odoo-dev/odoo/addons/stock_orderpoint_uom/models/procurement_group.py", line 23, in run
    name, origin, values)
  File "/home/odoo11/odoo-dev/odoo/addons/stock/models/procurement.py", line 186, in run
    getattr(rule, '_run_%s' % rule.action)(product_id, product_qty, product_uom, location_id, name, origin, values)
  File "/home/odoo11/odoo-dev/odoo/addons/stock/models/procurement.py", line 78, in _run_move
    data = self._get_stock_move_values(product_id, product_qty, product_uom, location_id, name, origin, values, group_id)
  File "/home/odoo11/odoo-dev/odoo/addons/sale_stock/models/stock.py", line 65, in _get_stock_move_values
    result = super(ProcurementRule, self)._get_stock_move_values(product_id, product_qty, product_uom, location_id, name, origin, values, group_id)
  File "/home/odoo11/odoo-dev/odoo/addons/stock_warehouse_calendar/models/procurement_rule.py", line 15, in _get_stock_move_values
    location_id, name, origin, values, group_id)
  File "/home/odoo11/odoo-dev/odoo/addons/stock_orderpoint_move_link/models/procurement_rule.py", line 14, in _get_stock_move_values
    location_id, name, origin, values, group_id)
  File "/home/odoo11/odoo-dev/odoo/addons/stock/models/procurement.py", line 91, in _get_stock_move_values
    date_expected = (datetime.strptime(values['date_planned'], DEFAULT_SERVER_DATETIME_FORMAT) - relativedelta(days=self.delay or 0)).strftime(DEFAULT_SERVER_DATETIME_FORMAT)
  File "/usr/lib/python3.5/_strptime.py", line 510, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.5/_strptime.py", line 343, in _strptime
    (data_string, format))
ValueError: time data '2018-08-28' does not match format '%Y-%m-%d %H:%M:%S'

**Comment by JordiBForgeFlow** [comment]
@lreficent can you take a look?

**Comment by LoisRForgeFlow** [comment]
Hi @ccandito

The functionality related to `mrp_nbr_days` haven't been ported and tested yet, I should have written it in the roadmap or hide the fields. I'll do it.

So, please, could you try again setting `mrp_nbr_days` to 0?

**Comment by LoisRForgeFlow** [comment]
No more issues reported, closing it.
