### ISSUE TITLE
MRP Multi level : raw material procurement 

### ISSUE THREAD

**Issue by ccandito** [OCA/manufacture#312]
Dear All,
I've run the procurement for a raw material from 'MRP inventory' view and the following error's occurred:
Thanks
Claudio

Traceback (most recent call last):
  File "/home/odoo11/odoo/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo11/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo11/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/odoo11/odoo/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo11/odoo/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo11/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo11/odoo/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo11/odoo/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/home/odoo11/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo11/odoo/addons/web/controllers/main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo11/odoo/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo11/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/odoo11/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo11/odoo/addons/mrp_multi_level/wizards/mrp_inventory_procure.py", line 81, in make_procurement
    values
  File "/home/odoo11/odoo/addons/stock_orderpoint_uom/models/procurement_group.py", line 23, in run
    name, origin, values)
  File "/home/odoo11/odoo/addons/stock/models/procurement.py", line 186, in run
    getattr(rule, '_run_%s' % rule.action)(product_id, product_qty, product_uom, location_id, name, origin, values)
  File "/home/odoo11/odoo/addons/stock/models/procurement.py", line 78, in _run_move
    data = self._get_stock_move_values(product_id, product_qty, product_uom, location_id, name, origin, values, group_id)
  File "/home/odoo11/odoo/addons/sale_stock/models/stock.py", line 65, in _get_stock_move_values
    result = super(ProcurementRule, self)._get_stock_move_values(product_id, product_qty, product_uom, location_id, name, origin, values, group_id)
  File "/home/odoo11/odoo/addons/stock_warehouse_calendar/models/procurement_rule.py", line 15, in _get_stock_move_values
    location_id, name, origin, values, group_id)
  File "/home/odoo11/odoo/addons/stock_orderpoint_move_link/models/procurement_rule.py", line 14, in _get_stock_move_values
    location_id, name, origin, values, group_id)
  File "/home/odoo11/odoo/addons/stock/models/procurement.py", line 91, in _get_stock_move_values
    date_expected = (datetime.strptime(values['date_planned'], DEFAULT_SERVER_DATETIME_FORMAT) - relativedelta(days=self.delay or 0)).strftime(DEFAULT_SERVER_DATETIME_FORMAT)
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '2018-10-10' does not match format '%Y-%m-%d %H:%M:%S'

**Comment by LoisRForgeFlow** [comment]
This only happens in runbot, if you try on your local/server it should work.

Anyway, I should have a look to fix that in runbot too. Will come back to this when I have some spare time.
