### ISSUE TITLE
mrp_bom_tracking for 13 version issue

### ISSUE THREAD

**Issue by szegc** [OCA/manufacture#522]
Hello guys,

      Below are detail log for mrp_bom_tracking model testing result, try to change value in bom_line_ids, issue occurred like below: TypeError: _get_tracked_fields() missing 1 required positional argument: 'updated_fields'

Odoo Server Error

Traceback (most recent call last):
  File "D:\odoo13\odoo\odoo\http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "D:\odoo13\odoo\odoo\http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "D:\odoo13\odoo\odoo\tools\pycompat.py", line 14, in reraise
    raise value
  File "D:\odoo13\odoo\odoo\http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "D:\odoo13\odoo\odoo\http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "D:\odoo13\odoo\odoo\service\model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "D:\odoo13\odoo\odoo\http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "D:\odoo13\odoo\odoo\http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "D:\odoo13\odoo\odoo\http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "D:\odoo13\odoo\addons\web\controllers\main.py", line 1322, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "D:\odoo13\odoo\addons\web\controllers\main.py", line 1314, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "D:\odoo13\odoo\odoo\api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "D:\odoo13\odoo\odoo\api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "d:\odoo13\temp\mrp_bom_tracking\models\mrp_bom.py", line 35, in write
    res = super(MrpBom, self).write(values)
  File "D:\odoo13\odoo\addons\mrp\models\mrp_bom.py", line 131, in write
    res = super().write(values)
  File "D:\odoo13\odoo\addons\mail\models\mail_thread.py", line 316, in write
    tracked_fields = track_self._get_tracked_fields()
TypeError: _get_tracked_fields() missing 1 required positional argument: 'updated_fields'

**Comment by LoisRForgeFlow** [comment]
Hi,

It is working perfectly for me. 

Please, try to reproduce in runbot and share the steps to get the error, then you can reopen the issue.
